/* Mockup 8 — the See / Secure / Govern story as data, shared by every variant.
 *
 * The section plays ONE clock, p 0..1 (See 0–0.34, Secure 0.34–0.67, Govern 0.67–1).
 * The close-up (each variant's scene.ts) plays storyboard time t (ms): See 0–5000,
 * Secure 5000–11000, Govern 11000–14600. netTime(p) → t and pOf(t) → p map between
 * them, so anything on the left changes exactly when the close-up shows its cause.
 *
 * EV lists the close-up's events. Every variant's scene.ts MUST keep these times
 * (it may change how they look, not when they happen), so any Left can pair with
 * any scene.
 *
 * Do not edit this file from a variant; derive what you need from Snap / p.
 */
import { sequence } from "@/mockups/9/content";

export type Stage = 0 | 1 | 2;

export const STAGES = sequence.stages;
export const DECISIONS = STAGES[0].decisions ?? ["Block", "Approve", "Protect", "Onboard"];
export const FRAMEWORKS = STAGES[2].frameworks ?? [];
export const CLAUSES = sequence.tagline.split(/(?<=,)\s+/); // "See it," "secure it," "govern it."

/** the close-up's events (storyboard ms) — the contract every scene keeps */
export const EV = {
  tabFlag: 2100, // "shadow AI · flagged": the personal chatgpt.com tab
  agentFlag: 4450, // "agent · flagged": agent:finance
  stripTouch: 5500, // the node touches the injected sentence (violet)
  stripDone: 7450, // collapsed into "[stripped · injected instruction]"
  maskStart: 8150, // bill-to data: the node touches
  maskDone: 8560, // lena.brandt@… → user_7f3a · IBAN → [masked]
  sendStart: 9000, // the agent's pointer sets off for "Send"
  sendClick: 9500, // the click lands on the node
  blocked: 9900, // "blocked · logged"
  foldStart: 11450, // Govern: finds fold into the log, 120 ms apart
  seal: 12450, // the mark presses the log: sealed
  evidence: 13000,
  end: 14600,
} as const;

/* ---------------- the two clocks ---------------- */
export const STAGE_P = [0.34, 0.67] as const;
export const BOUNDS = [0, STAGE_P[0], STAGE_P[1], 1];
export const pOf = (ms: number) =>
  ms < 5000
    ? (ms / 5000) * STAGE_P[0]
    : ms < 11000
      ? STAGE_P[0] + ((ms - 5000) / 6000) * (STAGE_P[1] - STAGE_P[0])
      : STAGE_P[1] + ((ms - 11000) / 3600) * (1 - STAGE_P[1]);
export const netTime = (p: number) =>
  p < BOUNDS[1]
    ? (p / BOUNDS[1]) * 5000
    : p < BOUNDS[2]
      ? 5000 + ((p - BOUNDS[1]) / (BOUNDS[2] - BOUNDS[1])) * 6000
      : 11000 + ((p - BOUNDS[2]) / (1 - BOUNDS[2])) * 3600;

/** Settled end state of each stage (stills, reduced motion, a click on a step). */
export const SETTLED = [0.33, 0.66, 1];
/** Playback: ms per stage (the close-up's beats), and the hold before it loops. */
/** PACE stretches the playback so every caption can be read as it lands (owner: "too fast").
 *  The close-up still draws storyboard time t = netTime(p); only the clock runs slower. */
export const PACE = 1.8;
export const STAGE_MS = [5000, 6000, 3600].map((ms) => ms * PACE);
export const HOLD_MS = 5200;

export const clamp01 = (x: number) => (x < 0 ? 0 : x > 1 ? 1 : x);
export const seg = (p: number, a: number, b: number) => clamp01((p - a) / (b - a));
export const stageOf = (p: number): Stage => (p < STAGE_P[0] ? 0 : p < STAGE_P[1] ? 1 : 2);
export const stageLocal = (p: number, k: number) => seg(p, BOUNDS[k], BOUNDS[k + 1]);

/* ---------------- the cast and what happens to it ---------------- */

/** See — the inventory. On record when the section opens, then the close-up's two finds. */
export const INVENTORY = [
  { name: "crm-assistant", where: "ws-sal-01", decision: 0 },
  { name: "agent:support", where: "rack-01 · customer IBANs in the page", decision: 2 },
  { name: "n8n", where: "n8n · invoices", decision: 1 },
];
export const FINDS = [
  { name: "chatgpt.com", where: "personal account · ws-fin-01", decision: 2, at: pOf(EV.tabFlag), label: "shadow AI" },
  { name: "agent:finance", where: "ws-fin-01", decision: 2, at: pOf(EV.agentFlag), label: "agent" },
];
/** a find is "current" this long (no decision yet), then its decision lands */
export const DECIDE = 0.05;

/** Secure — what the close-up does, in its order. */
export type RtEvent = { sys: string; obj: string; doing: string; done: string; note: string; t0: number; t1: number };
export const RUNTIME: RtEvent[] = [
  { sys: "agent:finance", obj: "invoice_0412.pdf", doing: "Stripping", done: "Stripped", note: "Hidden instruction removed before the agent acts on it", t0: pOf(EV.stripTouch), t1: pOf(EV.stripDone) },
  { sys: "agent:finance", obj: "bill-to data", doing: "Masking", done: "Masked", note: "lena.brandt@… → user_7f3a · IBAN → [masked]", t0: pOf(EV.maskStart), t1: pOf(EV.maskDone) },
  { sys: "agent:finance", obj: "send_email → ext-sync.io", doing: "Blocking", done: "Blocked", note: "Send blocked before it left", t0: pOf(EV.sendStart), t1: pOf(EV.blocked) },
];
/** handled earlier today, elsewhere in the fleet: settled, never animated (optional to show) */
export const EARLIER = [
  { sys: "crm-assistant", obj: "ws-sal-01", done: "Blocked", policy: "REG-01", note: "Access blocked pending approval", at: "14:29" },
  { sys: "agent:support", obj: "rack-01", done: "Masked", policy: "DATA-04", note: "IBANs masked before they reach agent:support", at: "14:30" },
];

/** Govern — the rows the close-up's log writes (same rows, same words), then sealed. */
export type LedgerRow = { id: string; time: string; finding: string; subject: string; policy: string; verdict: string };
export const LEDGER: LedgerRow[] = [
  { id: "0412-01", time: "14:31:40", finding: "shadow AI", subject: "chatgpt.com · personal", policy: "DATA-02", verdict: "flagged" },
  { id: "0412-02", time: "14:31:52", finding: "agent", subject: "agent:finance", policy: "AGENT-07", verdict: "flagged" },
  { id: "0412-03", time: "14:32:01", finding: "injection", subject: "invoice_0412.pdf", policy: "AGENT-07", verdict: "stripped" },
  { id: "0412-04", time: "14:32:03", finding: "private data", subject: "lena.brandt@… · IBAN", policy: "DATA-04", verdict: "masked" },
  { id: "0412-05", time: "14:32:07", finding: "tool call", subject: "send_email → ext-sync.io", policy: "AGENT-07", verdict: "blocked" },
];
/** each row lands as the close-up's fold paints it (fly 280 ms + paint, 120 ms apart) */
export const LEDGER_AT = LEDGER.map((_, k) => pOf(EV.foldStart + 370 + k * 120));
export const SEALED = { ref: "AT-0412", at: "14:32:12", hash: "sha256 7c1e…a90f", p: pOf(EV.seal) };
export const EVIDENCE_P = pOf(EV.evidence);
const HOLD_DOT = 0.03;

/* ---------------- the snapshot every Left renders from ---------------- */
export type Snap = {
  /** section progress, quantised to 0.005 (enough for eased reveals; keeps renders cheap) */
  p: number;
  stage: Stage;
  /** See: FINDS[i] has appeared / has its decision */
  found: boolean[];
  decided: boolean[];
  /** Secure: RUNTIME index being acted on (or -1), and which are done */
  acting: number;
  handled: boolean[];
  /** Govern: LEDGER rows written, the seal, the evidence */
  written: boolean[];
  sealed: boolean;
  evidence: boolean;
  /** the one event happening right now (the only thing allowed the live violet dot), or -1:
   *  See → FINDS index · Secure → RUNTIME index · Govern → LEDGER index */
  current: number;
};

/** the LATEST event whose window is open (windows overlap when rows land 120 ms apart) */
const lastIndex = <T,>(xs: readonly T[], f: (x: T) => boolean) => {
  for (let i = xs.length - 1; i >= 0; i--) if (f(xs[i])) return i;
  return -1;
};
function currentAt(p: number) {
  const st = stageOf(p);
  if (st === 0) return lastIndex(FINDS, (f) => p >= f.at && p < f.at + DECIDE);
  if (st === 1) return lastIndex(RUNTIME, (e) => p >= e.t0 && p < e.t1 + HOLD_DOT);
  // Govern: the dot rides the row being written, until the next one lands; it goes out at the seal
  if (p >= SEALED.p) return -1;
  return lastIndex(LEDGER_AT, (t) => p >= t);
}

export function snapAt(p: number): Snap {
  return {
    p: Math.round(p * 200) / 200,
    stage: stageOf(p),
    found: FINDS.map((f) => p >= f.at),
    decided: FINDS.map((f) => p >= f.at + DECIDE),
    acting: RUNTIME.findIndex((e) => p >= e.t0 && p < e.t1),
    handled: RUNTIME.map((e) => p >= e.t1),
    written: LEDGER_AT.map((t) => p >= t),
    sealed: p >= SEALED.p,
    evidence: p >= EVIDENCE_P,
    current: currentAt(p),
  };
}
export const count = (b: boolean[]) => b.filter(Boolean).length;

/* ---------------- the variant contract ---------------- */
export type LeftProps = { snap: Snap; theme: "light" | "dark" };
/** Stacked (phone / reduced motion): one block per stage, at its settled snapshot. */
export type StillProps = { snap: Snap; stage: Stage; theme: "light" | "dark" };
