/* The parts of three.js the site uses, re-exported so core.ts can hand scenes a `THREE`
   namespace without shipping the whole library: `import * as THREE from "three"` (passed on
   as a value) keeps every export, about 150 KB more for phones to download and parse.
   A scene that needs another class fails the type check until it is added here. */
export {
  AmbientLight,
  BackSide,
  BoxGeometry,
  BufferAttribute,
  BufferGeometry,
  CanvasTexture,
  CircleGeometry,
  Color,
  CylinderGeometry,
  DataTexture,
  DataUtils,
  DirectionalLight,
  DoubleSide,
  EdgesGeometry,
  EquirectangularReflectionMapping,
  Euler,
  ExtrudeGeometry,
  Float32BufferAttribute,
  FrontSide,
  Group,
  HalfFloatType,
  IcosahedronGeometry,
  InstancedMesh,
  LatheGeometry,
  LineBasicMaterial,
  LineSegments,
  LinearFilter,
  LinearMipmapLinearFilter,
  LinearSRGBColorSpace,
  Material,
  MathUtils,
  Matrix4,
  Mesh,
  MeshBasicMaterial,
  MeshPhysicalMaterial,
  MeshStandardMaterial,
  MultiplyBlending,
  NeutralToneMapping,
  NoColorSpace,
  NoToneMapping,
  Object3D,
  PMREMGenerator,
  Path,
  PerspectiveCamera,
  Plane,
  PlaneGeometry,
  Quaternion,
  RGBAFormat,
  RingGeometry,
  SRGBColorSpace,
  Scene,
  ShaderChunk,
  ShaderMaterial,
  Shape,
  ShapeGeometry,
  ShapeUtils,
  SphereGeometry,
  Texture,
  TorusGeometry,
  Vector2,
  Vector3,
  Vector4,
  WebGLRenderer,
} from "three";
export type { MeshPhysicalMaterialParameters } from "three";
