/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShadowRouteImport } from './routes/shadow'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MockupsRouteImport } from './routes/mockups'
import { Route as MockupLabRouteImport } from './routes/mockup-lab'
import { Route as Mockup8RouteImport } from './routes/mockup-8'
import { Route as Mockup7RouteImport } from './routes/mockup-7'
import { Route as Mockup6RouteImport } from './routes/mockup-6'
import { Route as Mockup5RouteImport } from './routes/mockup-5'
import { Route as Mockup4RouteImport } from './routes/mockup-4'
import { Route as Mockup3RouteImport } from './routes/mockup-3'
import { Route as Mockup2RouteImport } from './routes/mockup-2'
import { Route as Mockup1RouteImport } from './routes/mockup-1'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as HowToSecureLlmsRouteImport } from './routes/how-to-secure-llms'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiThreatDetectionRouteImport } from './routes/ai-threat-detection'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as CareersApplyRouteImport } from './routes/careers_.apply'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthorsSlugRouteImport } from './routes/authors.$slug'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowRoute = ShadowRouteImport.update({
  id: '/shadow',
  path: '/shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupsRoute = MockupsRouteImport.update({
  id: '/mockups',
  path: '/mockups',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupLabRoute = MockupLabRouteImport.update({
  id: '/mockup-lab',
  path: '/mockup-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const Mockup8Route = Mockup8RouteImport.update({
  id: '/mockup-8',
  path: '/mockup-8',
  getParentRoute: () => rootRouteImport,
} as any)
const Mockup7Route = Mockup7RouteImport.update({
  id: '/mockup-7',
  path: '/mockup-7',
  getParentRoute: () => rootRouteImport,
} as any)
const Mockup6Route = Mockup6RouteImport.update({
  id: '/mockup-6',
  path: '/mockup-6',
  getParentRoute: () => rootRouteImport,
} as any)
const Mockup5Route = Mockup5RouteImport.update({
  id: '/mockup-5',
  path: '/mockup-5',
  getParentRoute: () => rootRouteImport,
} as any)
const Mockup4Route = Mockup4RouteImport.update({
  id: '/mockup-4',
  path: '/mockup-4',
  getParentRoute: () => rootRouteImport,
} as any)
const Mockup3Route = Mockup3RouteImport.update({
  id: '/mockup-3',
  path: '/mockup-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Mockup2Route = Mockup2RouteImport.update({
  id: '/mockup-2',
  path: '/mockup-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Mockup1Route = Mockup1RouteImport.update({
  id: '/mockup-1',
  path: '/mockup-1',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToSecureLlmsRoute = HowToSecureLlmsRouteImport.update({
  id: '/how-to-secure-llms',
  path: '/how-to-secure-llms',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiThreatDetectionRoute = AiThreatDetectionRouteImport.update({
  id: '/ai-threat-detection',
  path: '/ai-threat-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const CareersApplyRoute = CareersApplyRouteImport.update({
  id: '/careers_/apply',
  path: '/careers/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/authors/$slug',
  path: '/authors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-threat-detection': typeof AiThreatDetectionRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/how-to-secure-llms': typeof HowToSecureLlmsRoute
  '/imprint': typeof ImprintRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mockup-1': typeof Mockup1Route
  '/mockup-2': typeof Mockup2Route
  '/mockup-3': typeof Mockup3Route
  '/mockup-4': typeof Mockup4Route
  '/mockup-5': typeof Mockup5Route
  '/mockup-6': typeof Mockup6Route
  '/mockup-7': typeof Mockup7Route
  '/mockup-8': typeof Mockup8Route
  '/mockup-lab': typeof MockupLabRoute
  '/mockups': typeof MockupsRoute
  '/privacy': typeof PrivacyRoute
  '/shadow': typeof ShadowRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/careers/apply': typeof CareersApplyRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-threat-detection': typeof AiThreatDetectionRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/how-to-secure-llms': typeof HowToSecureLlmsRoute
  '/imprint': typeof ImprintRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mockup-1': typeof Mockup1Route
  '/mockup-2': typeof Mockup2Route
  '/mockup-3': typeof Mockup3Route
  '/mockup-4': typeof Mockup4Route
  '/mockup-5': typeof Mockup5Route
  '/mockup-6': typeof Mockup6Route
  '/mockup-7': typeof Mockup7Route
  '/mockup-8': typeof Mockup8Route
  '/mockup-lab': typeof MockupLabRoute
  '/mockups': typeof MockupsRoute
  '/privacy': typeof PrivacyRoute
  '/shadow': typeof ShadowRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/careers/apply': typeof CareersApplyRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-threat-detection': typeof AiThreatDetectionRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/how-to-secure-llms': typeof HowToSecureLlmsRoute
  '/imprint': typeof ImprintRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mockup-1': typeof Mockup1Route
  '/mockup-2': typeof Mockup2Route
  '/mockup-3': typeof Mockup3Route
  '/mockup-4': typeof Mockup4Route
  '/mockup-5': typeof Mockup5Route
  '/mockup-6': typeof Mockup6Route
  '/mockup-7': typeof Mockup7Route
  '/mockup-8': typeof Mockup8Route
  '/mockup-lab': typeof MockupLabRoute
  '/mockups': typeof MockupsRoute
  '/privacy': typeof PrivacyRoute
  '/shadow': typeof ShadowRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/careers_/apply': typeof CareersApplyRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-threat-detection'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/demo'
    | '/docs'
    | '/faq'
    | '/how-to-secure-llms'
    | '/imprint'
    | '/llms.txt'
    | '/mockup-1'
    | '/mockup-2'
    | '/mockup-3'
    | '/mockup-4'
    | '/mockup-5'
    | '/mockup-6'
    | '/mockup-7'
    | '/mockup-8'
    | '/mockup-lab'
    | '/mockups'
    | '/privacy'
    | '/shadow'
    | '/sitemap.xml'
    | '/team'
    | '/authors/$slug'
    | '/blog/$slug'
    | '/careers/apply'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-threat-detection'
    | '/careers'
    | '/contact'
    | '/demo'
    | '/docs'
    | '/faq'
    | '/how-to-secure-llms'
    | '/imprint'
    | '/llms.txt'
    | '/mockup-1'
    | '/mockup-2'
    | '/mockup-3'
    | '/mockup-4'
    | '/mockup-5'
    | '/mockup-6'
    | '/mockup-7'
    | '/mockup-8'
    | '/mockup-lab'
    | '/mockups'
    | '/privacy'
    | '/shadow'
    | '/sitemap.xml'
    | '/team'
    | '/authors/$slug'
    | '/blog/$slug'
    | '/careers/apply'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/ai-threat-detection'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/demo'
    | '/docs'
    | '/faq'
    | '/how-to-secure-llms'
    | '/imprint'
    | '/llms.txt'
    | '/mockup-1'
    | '/mockup-2'
    | '/mockup-3'
    | '/mockup-4'
    | '/mockup-5'
    | '/mockup-6'
    | '/mockup-7'
    | '/mockup-8'
    | '/mockup-lab'
    | '/mockups'
    | '/privacy'
    | '/shadow'
    | '/sitemap.xml'
    | '/team'
    | '/authors/$slug'
    | '/blog/$slug'
    | '/careers_/apply'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiThreatDetectionRoute: typeof AiThreatDetectionRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRoute
  FaqRoute: typeof FaqRoute
  HowToSecureLlmsRoute: typeof HowToSecureLlmsRoute
  ImprintRoute: typeof ImprintRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  Mockup1Route: typeof Mockup1Route
  Mockup2Route: typeof Mockup2Route
  Mockup3Route: typeof Mockup3Route
  Mockup4Route: typeof Mockup4Route
  Mockup5Route: typeof Mockup5Route
  Mockup6Route: typeof Mockup6Route
  Mockup7Route: typeof Mockup7Route
  Mockup8Route: typeof Mockup8Route
  MockupLabRoute: typeof MockupLabRoute
  MockupsRoute: typeof MockupsRoute
  PrivacyRoute: typeof PrivacyRoute
  ShadowRoute: typeof ShadowRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  AuthorsSlugRoute: typeof AuthorsSlugRoute
  CareersApplyRoute: typeof CareersApplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadow': {
      id: '/shadow'
      path: '/shadow'
      fullPath: '/shadow'
      preLoaderRoute: typeof ShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockups': {
      id: '/mockups'
      path: '/mockups'
      fullPath: '/mockups'
      preLoaderRoute: typeof MockupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup-lab': {
      id: '/mockup-lab'
      path: '/mockup-lab'
      fullPath: '/mockup-lab'
      preLoaderRoute: typeof MockupLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup-8': {
      id: '/mockup-8'
      path: '/mockup-8'
      fullPath: '/mockup-8'
      preLoaderRoute: typeof Mockup8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup-7': {
      id: '/mockup-7'
      path: '/mockup-7'
      fullPath: '/mockup-7'
      preLoaderRoute: typeof Mockup7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup-6': {
      id: '/mockup-6'
      path: '/mockup-6'
      fullPath: '/mockup-6'
      preLoaderRoute: typeof Mockup6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup-5': {
      id: '/mockup-5'
      path: '/mockup-5'
      fullPath: '/mockup-5'
      preLoaderRoute: typeof Mockup5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup-4': {
      id: '/mockup-4'
      path: '/mockup-4'
      fullPath: '/mockup-4'
      preLoaderRoute: typeof Mockup4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup-3': {
      id: '/mockup-3'
      path: '/mockup-3'
      fullPath: '/mockup-3'
      preLoaderRoute: typeof Mockup3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup-2': {
      id: '/mockup-2'
      path: '/mockup-2'
      fullPath: '/mockup-2'
      preLoaderRoute: typeof Mockup2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup-1': {
      id: '/mockup-1'
      path: '/mockup-1'
      fullPath: '/mockup-1'
      preLoaderRoute: typeof Mockup1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-secure-llms': {
      id: '/how-to-secure-llms'
      path: '/how-to-secure-llms'
      fullPath: '/how-to-secure-llms'
      preLoaderRoute: typeof HowToSecureLlmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-threat-detection': {
      id: '/ai-threat-detection'
      path: '/ai-threat-detection'
      fullPath: '/ai-threat-detection'
      preLoaderRoute: typeof AiThreatDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/careers_/apply': {
      id: '/careers_/apply'
      path: '/careers/apply'
      fullPath: '/careers/apply'
      preLoaderRoute: typeof CareersApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiThreatDetectionRoute: AiThreatDetectionRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRoute,
  FaqRoute: FaqRoute,
  HowToSecureLlmsRoute: HowToSecureLlmsRoute,
  ImprintRoute: ImprintRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  Mockup1Route: Mockup1Route,
  Mockup2Route: Mockup2Route,
  Mockup3Route: Mockup3Route,
  Mockup4Route: Mockup4Route,
  Mockup5Route: Mockup5Route,
  Mockup6Route: Mockup6Route,
  Mockup7Route: Mockup7Route,
  Mockup8Route: Mockup8Route,
  MockupLabRoute: MockupLabRoute,
  MockupsRoute: MockupsRoute,
  PrivacyRoute: PrivacyRoute,
  ShadowRoute: ShadowRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  AuthorsSlugRoute: AuthorsSlugRoute,
  CareersApplyRoute: CareersApplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
